version: '2'
services:
  db:
    image: postgres:9.5
    volumes:
      - ${APP_DB_DIR}:${PGDATA}
      - ./setup:/docker-entrypoint-initdb.d
    env_file:
      - ./app.env
      - ./db.env
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: ${APP_DB_USER}:beta
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ${APP_PATH}:/usr/src/app
    env_file:
      - ./app.env
      - ./db.env
    ports:
      - "3000:3000"
    depends_on:
      - db
