CREATE USER ${APP_DB_USER} WITH PASSWORD '${APP_DB_PASS}';
CREATE DATABASE ${APP_DB_NAME};
GRANT ALL PRIVILEGES ON DATABASE ${APP_DB_NAME} TO ${APP_DB_USER};
CREATE DATABASE ${APP_DEV_DB_NAME};
GRANT ALL PRIVILEGES ON DATABASE ${APP_DB_NAME}_dev TO ${APP_DB_USER};
CREATE DATABASE ${APP_TEST_DB_NAME};
GRANT ALL PRIVILEGES ON DATABASE ${APP_DB_NAME}_test TO ${APP_DB_USER};
